### ISSUE TITLE
Rationalize RepositoryCopy.CopyStatus vis-à-vis transfer of custody

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-data-model#35]
### Overview

The primary responsibility of [Deposit Services](https://github.com/OA-PASS/nihms-submission) is supporting the transfer of custody of submitted materials from the end-user to the Fedora repository, and managing the transfer of custody from the Fedora repository to downstream repositories.  Understanding that downstream repositories have different interaction models and capabilities, it is imperative that Deposit Services (i.e. the PASS data model) have an abstract notion for representing the success or failure of custody transfer.

Currently, the success or failure of custody transfer to a single downstream repository is represented by the status of `Deposit` (and at a higher level on the derived `Submission`).  

If Deposit Services does not manage a custody transfer then there will be no `Deposit` resource, and therefore no reason to record the success or failure of such a transfer.  This may occur when the end-user of the UI is directed to submit their content directly to a downstream repository.  If Deposit Services does manage a custody transfer, a `Deposit` will be created, and the ultimate success or failure of the custody transfer will be recorded on the `DepositStatus` field.

### Interaction Models and Custody Transfer

As noted above, because downstream repositories have different capabilities, the interaction of Deposit Services with those repositories may vary at a high level:
* Deposit Services may not interact at all (as when the user submits their content directly to the downstream repository)
* Deposit Services may be responsible for the entire interaction with the downstream repository (as with DSpace SWORD deposits)
* Deposit Services may only be responsible for providing the content to the downstream repository (as with PubMed deposits)

At a lower level, there is quite a bit of nuance.  For example, when interacting with DSpace SWORD repositories, Deposit Services must create a `RepositoryCopy` resource to store the `accessUrl` (i.e. the DSpace Item URL) returned by a SWORD deposit because that information is not stored anywhere else.  That is to say, the information provided by a DSpace SWORD deposit "receipt" is ephemeral state unless it is stored by Deposit Services.  The interaction with DSpace SWORD requires the creation of a `RepositoryCopy` _prior to the successful transfer of custody_.

The take home point is that it is near impossible impossible to know what downstream repositories are going to require of Deposit Services, and what impact they may have on the PASS data model.  In other words, _the presence or absence of a resource_ in the abstract cannot be used to imply anything about the transfer of custody.

### The Argument

The argument presented in this issue is that the mere presence of `RepositoryCopy` cannot and should not be used to imply successful transfer of custody.  Furthermore, there should be a single status that represents successful transfer of custody, and a single status that represents a failed transfer of custody.

### Status and Transfer of Custody

For reference, Deposit Services relies on status fields to record successful transfers of custody.  The primary status is recorded on `Deposit`, and a derived status is calculated by Deposit Services and placed on the higher level `Submission` associated with the `Deposit`.  The status flags used by Deposit Services are defined [here](https://github.com/OA-PASS/nihms-submission#status).

### RepositoryCopy CopyStatus 

The presence of _any_ form of _intermediate_ status (such as `IN_PROGRESS`) in the PASS model implies that a `RepositoryCopy` status can transition to _terminal_ in the future.  Because it is impossible to know the interaction models of downstream repositories, we must consider that a successful _terminal_ outcome is just as possible as an unsuccessful one, and the PASS model should accommodate this.  The variations in the two different repositories we interact with now argue for this.

The `RepositoryCopy` `CopyStatus` may influence the notion of a successful transfer of custody. 
 Because the interaction models are not able to be anticipated we must consider what happens when a `RepositoryCopy` ends up being `REJECTED`.  In this case, the transfer of custody was not successful, and the `Deposit` status must be updated accordingly.  

This issue proposes a rationalization of `CopyStatus` as follows:
* `REJECTED` (_terminal_): custody was not accepted by the `Repository`, and any state on the `RepositoryCopy` cannot be reliably used for any purpose.
* `ACCEPTED` (_terminal_): custody was accepted by the `Repository`, and any state on the `RepositoryCopy` is considered final.
* `IN_PROGRESS` (_intermediate_): custody transfer is in progress, and any state on the `RepositoryCopy` is considered *provisional* until the state flips to `ACCEPTED`.

I would do away with `STALLED` and `COMPLETE` statuses, but if they remain, they should have defined semantics (vis-a-vis how the state of the RepoCopy is to be interpreted) and they should be considered _intermediate_ and not _terminal_ (unless the difference between three or more terminal states can be defined vis-a-vis custodial transfer).

**Comment by emetsger** [comment]
Other options may exist, too.  For example, updating the model (or Deposit Services code) to remove any reliance on `RepositoryCopy` for determining the successful transfer of custody.  This would mean, among other things, that Deposit Services is not the sole "manager" of the status of `Deposit`, which may have some consequences that should be explored.

**Comment by karenhanson** [comment]
@emetsger I need a few more pieces of information in order to think about this more:
(1) what does the receipt from SWORD look like and and what does it mean. Is it a final URI for the submission, e.g. a handle? or just a receipt.
(2) If once you have this receipt URI the package is found to have problems in DSpace, what does that look like and what can PASS do about it? I am unfamiliar with the SWORD/DSpace dance. 
(3) How is the "Deposit.depositStatusRef" is being used for DSpace - my understanding is that this was to hold a URI that can be used to check on status until a persistent ID is available for RepositoryCopy creation.

I am reluctant to link RepositoryCopy to Deposit but wondering if there is a field we can add to one or both that will make linkage clearer - I think that might be in the same vein as your last comment about not depending on RepositoryCopy for status.

**Comment by emetsger** [comment]
@karenhanson If we don't link RepositoryCopy to Deposit, then RepositoryCopy _must_ not carry any semantics about custody transfer (which is fine, if that's what we decide).

> (1) what does the receipt from SWORD look like and and what does it mean. Is it a final URI for the submission, e.g. a handle? or just a receipt.

The receipt is an XML document that has information about the deposit transaction (a [SWORD Receipt](http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#depositreceipt)).  It is distinct from the SWORD state (i.e. the url linked to by the `depositStatusRef`).  The receipt has no identity, and cannot be retrieved as far as I know.  It's ephemeral state.

The URI in this case it the URL to the Item in DSpace (a `<link rel="alternate">...</link>`).  It happens to be equivalent to the RepositoryCopy externalId, but that is not specified behavior.

> (2) If once you have this receipt URI the package is found to have problems in DSpace, what does that look like and what can PASS do about it? I am unfamiliar with the SWORD/DSpace dance.

If the deposit is rejected by DSpace, then the `Deposit` resource is marked as `REJECTED`.  Nothing can be done.

If there is a transient failure, the `Deposit` is marked as `FAILED`, and the `Deposit` can be retried.

But, most importantly, the `Deposit` can be marked (and remain) `SUBMITTED`, if DSpace chooses not to process the package immediately.  In *that* case, the ephemeral state on the receipt must be recorded somewhere, and the `Deposit` status refreshed later.  

> (3) How is the "Deposit.depositStatusRef" is being used for DSpace - my understanding is that this was to hold a URI that can be used to check on status until a persistent ID is available for RepositoryCopy creation.

`Deposit.depositStatusRef` is used to determine the success or failure of the transfer of custody.  It is a [SWORD Statement](http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#statement).  If the statement had an `accessUrl`, then we could also parse that out of the document, but it doesn't.  

The `Deposit.depositStatusRef` is what is consulted when a `Deposit` marked as `SUBMITTED` is refreshed.
