### ISSUE TITLE
Capture information about a submission in which the publishing journal is a method a journal

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-data-model#44]
When a manuscript citing method A journal is submitted, PASS does not move forward with the NIHMS submission to save users the effort. Currently, this interaction and determination leave no trace on the submission record and could cause confusion. To me info more apparent, update the model to capture this information for the record

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
